name: integration test

on:
  workflow_dispatch:
    secrets:
      AIVEN_TEST_KAFKA_CLUSTER:
        required: true
      AIVEN_TEST_KAFKA_PASSWORD:
        required: true

jobs:
  aiven-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          pip install .
          kafka-http-monitor test https://www.google.com.br \
            --kafka-cluster '${{ secrets.AIVEN_TEST_KAFKA_CLUSTER }}' \
            --kafka-sasl-certificate data/aiven-test-certificate.pem \
            --kafka-sasl-mechanism SCRAM-SHA-256 \
            --kafka-sasl-password '${{ secrets.AIVEN_TEST_KAFKA_PASSWORD }}' \
            --kakfa-sasl-username avnadmin \
            --kafka-security-protocol sasl_ssl
