name: check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install '.[lint]'
      - run: ruff src
      - run: black --check --diff src

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install '.[types]'
      - run: mypy src

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: pytest
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV: $VIRTUAL_ENV"
          pip install --upgrade pip
          pip install '.[test]'
          pytest -s -vv
